services:
  - type: web
    name: energy2-cashflow
    env: node
    plan: free
    buildCommand: |
      cd client && npm install && npm run build
      cd ../server && npm install
    startCommand: cd server && npm start
    healthCheckPath: /health
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: NODE_VERSION
        value: 18
    disk:
      name: data
      mountPath: /var/data
      sizeGB: 1
